### ISSUE TITLE
login

### ISSUE THREAD

**Issue by jimbling** [nomenklatur/laravel-bukuinduksiswa#1]
mas mau tanya, ini untuk login nya apa ya ? apa berbayar ? terima kasih

**Comment by nomenklatur** [comment]
> mas mau tanya, ini untuk login nya apa ya ? apa berbayar ? terima kasih

login-nya menggunakan email dan password mas.
user bisa login dengan akun siswa atau akun admin.
email dan password siswa dan admin udah saya provide di file seeder mas.
kalau ada yang mau ditanyain lagi monggo mas @jimbling
