### ISSUE TITLE
password

### ISSUE THREAD

**Issue by hexa06** [nomenklatur/laravel-bukuinduksiswa#2]
user dan passwordnya apa?

**Comment by nomenklatur** [comment]
> user dan passwordnya apa?

untuk user level Admin gunakan kredensial berikut:
email : adminweb@gmail.com
pass : admin123

untuk user level Siswa gunakan kredensial berikut:
email : tesakunsiswa@gmail.com
pass : siswa123

note: pastikan sudah menjalankan command `php artisan migrate --seed` ya

**Comment by syamuchiha** [comment]
Terima kasih banyak Gan

**Comment by nomenklatur** [comment]
Closed as of today
